### ISSUE TITLE
Check for calculate fails if a list is defined

### ISSUE THREAD

**Issue by simplect** [WincAcademy/wincpy#9]
wincpy check 499e67d5cb54448e93cee7465be2c866

If a user defined a variable with a list the following error is produced:

```Output From Your Program
The average is  3.5

Traceback (most recent call last):
  File "C:\Users\alexl\AppData\Local\Programs\Python\Python39\Scripts\wincpy-script.py", line 33, in <module>
    sys.exit(load_entry_point('wincpy==0.2.3.5', 'console_scripts', 'wincpy')())
  File "c:\users\alexl\appdata\local\programs\python\python39\lib\site-packages\wincpy\__main__.py", line 7, in console_entry
    main(sys.stdout, sys.stderr)
  File "c:\users\alexl\appdata\local\programs\python\python39\lib\site-packages\wincpy\main.py", line 18, in main
    result = check(args)
  File "c:\users\alexl\appdata\local\programs\python\python39\lib\site-packages\wincpy\main.py", line 85, in check
    result = check.run(student_module)
  File "c:\users\alexl\appdata\local\programs\python\python39\lib\site-packages\wincpy\checks\499e67d5cb54448e93cee7465be2c866.py", line 26, in run 
    result += compare_states(expected_state, assignment_state)
  File "c:\users\alexl\appdata\local\programs\python\python39\lib\site-packages\wincpy\helpers.py", line 68, in compare_states
    as_tupleset = set(actual_state.items())
TypeError: unhashable type: 'list'
```

Code to reproduce:
```# Do not modify these lines
__winc_id__ = '499e67d5cb54448e93cee7465be2c866'
__human_name__ = 'calculate'

test = []
```

**Comment by stfwn** [comment]
This is fixed in the new check module system (#8).
